import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    backgroundColor: '#5DB075',
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  card: {
    backgroundColor: 'white',
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 'auto',
    marginTop: 'auto',
    paddingTop: 32,
    paddingBottom: 32,
    paddingLeft: 16,
    paddingRight: 16,
    borderRadius: 20,
    shadowColor: 'rgba(38, 36, 131, 0.25)',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 1,
    shadowRadius: 30,
    elevation: 5,
  },
  texto: {
    color: '#777',
    fontFamily: 'sans-serif',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '100',
    lineHeight: 18,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 10,
  },
  titulo: {
    color: '#000',
    textAlign: 'center',
    fontFamily: 'sans-serif',
    fontSize: 22,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 25,
    marginBottom: 20,
  },
  imageWrapper: {
    width: '100%',
    position: 'absolute',
    top: 50,
    zIndex: 1,
  },
  image: {
    width: 200,
    height: 100,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  button: {
    borderRadius: 100,
    backgroundColor: '#5DB075',
    padding: 16,
    marginTop: 25,
  },
  buttonText: {
    textAlign: 'center',
    color: 'white',
    fontWeight: '500',
  },
});
