import {Dimensions, StyleSheet} from 'react-native';

const screenHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  container: {
    backgroundColor: '#5DB075',
    width: '100%',
    position: 'relative',
    display: 'flex',
    flex: 1,
    minHeight: screenHeight - 134,
    paddingBottom: 50,
  },
  card: {
    backgroundColor: 'white',
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 'auto',
    marginTop: 'auto',
    paddingTop: 32,
    paddingBottom: 32,
    paddingLeft: 16,
    paddingRight: 16,
    borderRadius: 20,
    shadowColor: 'rgba(38, 36, 131, 0.25)',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 1,
    shadowRadius: 30,
    elevation: 5,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  texto: {
    color: '#777',
    fontFamily: 'sans-serif',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '100',
    lineHeight: 19,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 15,
    textAlign: 'center',
  },
  titulo: {
    color: '#000',
    textAlign: 'center',
    fontFamily: 'sans-serif',
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 24,
    marginBottom: 0,
    marginTop: 15,
  },
  error: {
    backgroundColor: '#ffebee',
    color: '#a62216',
    textAlign: 'center',
    fontFamily: 'sans-serif',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 20,
    marginBottom: 20,
  },
  imageWrapper: {
    width: '100%',
    marginTop: 20,
    marginBottom: 20,
    // position: 'absolute',
    // top: 30,
    // zIndex: 1,
  },
  image: {
    width: 200,
    height: 100,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  button: {
    borderRadius: 100,
    backgroundColor: '#5DB075',
    padding: 16,
    marginTop: 25,
  },
  buttonText: {
    textAlign: 'center',
    color: 'white',
    fontWeight: '500',
  },

  conexionWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    marginBottom: 20,
  },
  conexionImageWrapper: {
    width: 100,
    height: 100,
    elevation: 45,
    borderRadius: 100,
    backgroundColor: 'white',
    shadowColor: '#000',
  },
  conexionImage: {width: 100, height: 100},
  menuSeleccion: {
    display: 'flex',
    flexDirection: 'row',
    marginTop: 10,
    paddingLeft: 40,
    paddingRight: 40,
    justifyContent: 'space-between',
    // gap: 40,
  },
  itemImage: {width: 70, height: 70},
  item: {display: 'flex', alignItems: 'center', justifyContent: 'center'},
  posContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 7,
    gap: 10,
  },
  posImage: {
    width: 20,
    height: 20,
  },
  posText: {
    color: '#1e3050',
    fontSize: 12,
    lineHeight: 12,
  },
});
